[tool.black]
line-length = 150

[tool.pylint]
generated-members = ["torch.*"]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "invalid-name",
  "line-too-long",
  "too-many-arguments",
]
